name: Push to registry
description: Publish docker image of the repository to the container registry
author: Mark Novak

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: upload-cloud
  color: blue

outputs:
  image_tag:
    description: The tag of the image to be deployed.
    value: ${{ steps.push-to-registry.outputs.image_tag }}
inputs:
  username:
    description: The username of the container registry account. Default to repository owner.
    required: false
    default: ${{ github.repository_owner }}
  password:
    description: Password or a personal access token for the container registry account.
    required: true
  publish:
    description: If true, it will publish the images to the specified registry.
    required: false
    default: 'true'
  registry:
    description: The container registry to commit the package to.
    default: ghcr.io
    required: false
  ref:
    description: The ref of the tag or branch to be pushed.
    required: true
  images:
    description: List of Docker images to use as base name for tags. Default {registry}/{owner}/{repository}
    required: false
  flavor:
    description: Flavor to apply.
    required: false
  tags:
    description: List of custom tags.
    required: false
  labels:
    description: List of custom labels.
    required: false
  annotations:
    description: list of custom annotations.
    required: false

runs:
  using: 'composite'
  steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      ref: ${{ inputs.ref }}

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Login to the container registry
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry }}
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}

  - name: Extract metadata (tags, labels) for Docker
    id: meta
    uses: docker/metadata-action@v5
    env:
      DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
    with:
      context: git
      flavor: ${{ inputs.flavor }}
      tags: ${{ inputs.tags }}
      annotations: ${{ inputs.annotations }}
      images: ${{inputs.images != '' && inputs.images || format('{0}/{1}', inputs.registry, github.repository)}}

  - name: Get image tag for deployment
    id: tag
    shell: bash
    run: |
      tag=$(echo '${{ steps.meta.outputs.json }}' | jq -r '.tags[0]')
      echo "image_tag=$tag" >> $GITHUB_OUTPUT

  - name: Build and push to registry
    id: push
    uses: docker/build-push-action@v5
    with:
      push: ${{ inputs.publish }}
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      annotations: ${{ steps.meta.outputs.annotations }}
